export const SKILL_DATA = {
  // Shadow Clone
  SHADOW_CLONE_CHANCE: 0.05,
  CLONE_COUNT_MIN: 1,
  CLONE_COUNT_MAX: 3,

  // Chain Lightning
  CHAIN_LIGHTNING_CHANCE: 0.05,
  CHAIN_SPLASH_COMBO: 0.5,
  CHAIN_SPLASH_SOLO: 1.0,
  CHAIN_COMBO_CHANCE: 0.7,

  // Freeze
  FREEZE_CHARGE_MIN: 1,
  FREEZE_CHARGE_MAX: 3,

  // True Strike
  TRUE_HIT_CHARGE_MIN: 1,
  TRUE_HIT_CHARGE_MAX: 3,

  // Reflect Chaos
  REFLECT_CHANCE: 0.1,
  REFLECT_COMBO_CHANCE: 0.7,
  REFLECT_COMBO_TAKE: 0.1,
  REFLECT_COMBO_SEND: 0.9,
  REFLECT_SOLO_TAKE: 0.0,
  REFLECT_SOLO_SEND: 1.0,

  // Hunter
  HUNTER_ACCURACY_BONUS: 0.1,
};
